// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package administrator.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the Administrator module
	public static void aCT_ApproveRegistrationRequest(IContext context, customer.proxies.Customer _customer)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Customer", _customer == null ? null : _customer.getMendixObject());
		Core.microflowCall("Administrator.ACT_ApproveRegistrationRequest").withParams(params).execute(context);
	}
	public static void aCT_CreateBackendUser(IContext context, administration.proxies.Account _account)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Account", _account == null ? null : _account.getMendixObject());
		Core.microflowCall("Administrator.ACT_CreateBackendUser").withParams(params).execute(context);
	}
	public static void aCT_RejectRegistrationRequest(IContext context, customer.proxies.Customer _customer)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Customer", _customer == null ? null : _customer.getMendixObject());
		Core.microflowCall("Administrator.ACT_RejectRegistrationRequest").withParams(params).execute(context);
	}
	public static void aCT_SaveUserDetails(IContext context, administration.proxies.Account _account)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Account", _account == null ? null : _account.getMendixObject());
		Core.microflowCall("Administrator.ACT_SaveUserDetails").withParams(params).execute(context);
	}
	public static void aCT_ShowWeatherConfiguration(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Administrator.ACT_ShowWeatherConfiguration").withParams(params).execute(context);
	}
	public static void dS_GetCurrentWeatherStatus(IContext context, customer.proxies.Customer _customer)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Customer", _customer == null ? null : _customer.getMendixObject());
		Core.microflowCall("Administrator.DS_GetCurrentWeatherStatus").withParams(params).execute(context);
	}
	public static void sub_SendEmail(IContext context, administrator.proxies.NotificationHolder _notificationHolder)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("NotificationHolder", _notificationHolder == null ? null : _notificationHolder.getMendixObject());
		Core.microflowCall("Administrator.Sub_SendEmail").withParams(params).execute(context);
	}
	public static boolean vAL_UserCreation(IContext context, administration.proxies.Account _account)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Account", _account == null ? null : _account.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("Administrator.VAL_UserCreation").withParams(params).execute(context);
	}
}
