// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package customer.proxies;

/**
 * RegistrationRequest description: 
 * 
 * - This enity allow the anonyous user to submit request for registartion for his/her custmer account.
 * - Once the Admin user accept the request customer user will be created for the user.
 */
public class Customer extends administration.proxies.Account
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Customer.Customer";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FirstName("FirstName"),
		LastName("LastName"),
		PhoneNumber("PhoneNumber"),
		Address1("Address1"),
		Address2("Address2"),
		City("City"),
		State("State"),
		Landmark("Landmark"),
		Zip("Zip"),
		RegistrationStatus("RegistrationStatus"),
		FullName("FullName"),
		Email("Email"),
		IsLocalUser("IsLocalUser"),
		Name("Name"),
		Password("Password"),
		LastLogin("LastLogin"),
		Blocked("Blocked"),
		BlockedSince("BlockedSince"),
		Active("Active"),
		FailedLogins("FailedLogins"),
		WebServiceUser("WebServiceUser"),
		IsAnonymous("IsAnonymous"),
		UserRoles("System.UserRoles"),
		User_Language("System.User_Language"),
		User_TimeZone("System.User_TimeZone");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Customer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Customer(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject customerMendixObject)
	{
		super(context, customerMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, customerMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * @deprecated Use 'Customer.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static customer.proxies.Customer initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return customer.proxies.Customer.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static customer.proxies.Customer initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new customer.proxies.Customer(context, mendixObject);
	}

	public static customer.proxies.Customer load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return customer.proxies.Customer.initialize(context, mendixObject);
	}

	public static java.util.List<customer.proxies.Customer> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> customer.proxies.Customer.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of FirstName
	 */
	public final java.lang.String getFirstName()
	{
		return getFirstName(getContext());
	}

	/**
	 * @param context
	 * @return value of FirstName
	 */
	public final java.lang.String getFirstName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FirstName.toString());
	}

	/**
	 * Set value of FirstName
	 * @param firstname
	 */
	public final void setFirstName(java.lang.String firstname)
	{
		setFirstName(getContext(), firstname);
	}

	/**
	 * Set value of FirstName
	 * @param context
	 * @param firstname
	 */
	public final void setFirstName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String firstname)
	{
		getMendixObject().setValue(context, MemberNames.FirstName.toString(), firstname);
	}

	/**
	 * @return value of LastName
	 */
	public final java.lang.String getLastName()
	{
		return getLastName(getContext());
	}

	/**
	 * @param context
	 * @return value of LastName
	 */
	public final java.lang.String getLastName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LastName.toString());
	}

	/**
	 * Set value of LastName
	 * @param lastname
	 */
	public final void setLastName(java.lang.String lastname)
	{
		setLastName(getContext(), lastname);
	}

	/**
	 * Set value of LastName
	 * @param context
	 * @param lastname
	 */
	public final void setLastName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String lastname)
	{
		getMendixObject().setValue(context, MemberNames.LastName.toString(), lastname);
	}

	/**
	 * @return value of PhoneNumber
	 */
	public final java.lang.String getPhoneNumber()
	{
		return getPhoneNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of PhoneNumber
	 */
	public final java.lang.String getPhoneNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PhoneNumber.toString());
	}

	/**
	 * Set value of PhoneNumber
	 * @param phonenumber
	 */
	public final void setPhoneNumber(java.lang.String phonenumber)
	{
		setPhoneNumber(getContext(), phonenumber);
	}

	/**
	 * Set value of PhoneNumber
	 * @param context
	 * @param phonenumber
	 */
	public final void setPhoneNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String phonenumber)
	{
		getMendixObject().setValue(context, MemberNames.PhoneNumber.toString(), phonenumber);
	}

	/**
	 * @return value of Address1
	 */
	public final java.lang.String getAddress1()
	{
		return getAddress1(getContext());
	}

	/**
	 * @param context
	 * @return value of Address1
	 */
	public final java.lang.String getAddress1(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Address1.toString());
	}

	/**
	 * Set value of Address1
	 * @param address1
	 */
	public final void setAddress1(java.lang.String address1)
	{
		setAddress1(getContext(), address1);
	}

	/**
	 * Set value of Address1
	 * @param context
	 * @param address1
	 */
	public final void setAddress1(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String address1)
	{
		getMendixObject().setValue(context, MemberNames.Address1.toString(), address1);
	}

	/**
	 * @return value of Address2
	 */
	public final java.lang.String getAddress2()
	{
		return getAddress2(getContext());
	}

	/**
	 * @param context
	 * @return value of Address2
	 */
	public final java.lang.String getAddress2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Address2.toString());
	}

	/**
	 * Set value of Address2
	 * @param address2
	 */
	public final void setAddress2(java.lang.String address2)
	{
		setAddress2(getContext(), address2);
	}

	/**
	 * Set value of Address2
	 * @param context
	 * @param address2
	 */
	public final void setAddress2(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String address2)
	{
		getMendixObject().setValue(context, MemberNames.Address2.toString(), address2);
	}

	/**
	 * @return value of City
	 */
	public final java.lang.String getCity()
	{
		return getCity(getContext());
	}

	/**
	 * @param context
	 * @return value of City
	 */
	public final java.lang.String getCity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.City.toString());
	}

	/**
	 * Set value of City
	 * @param city
	 */
	public final void setCity(java.lang.String city)
	{
		setCity(getContext(), city);
	}

	/**
	 * Set value of City
	 * @param context
	 * @param city
	 */
	public final void setCity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String city)
	{
		getMendixObject().setValue(context, MemberNames.City.toString(), city);
	}

	/**
	 * @return value of State
	 */
	public final java.lang.String getState()
	{
		return getState(getContext());
	}

	/**
	 * @param context
	 * @return value of State
	 */
	public final java.lang.String getState(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.State.toString());
	}

	/**
	 * Set value of State
	 * @param state
	 */
	public final void setState(java.lang.String state)
	{
		setState(getContext(), state);
	}

	/**
	 * Set value of State
	 * @param context
	 * @param state
	 */
	public final void setState(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String state)
	{
		getMendixObject().setValue(context, MemberNames.State.toString(), state);
	}

	/**
	 * @return value of Landmark
	 */
	public final java.lang.String getLandmark()
	{
		return getLandmark(getContext());
	}

	/**
	 * @param context
	 * @return value of Landmark
	 */
	public final java.lang.String getLandmark(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Landmark.toString());
	}

	/**
	 * Set value of Landmark
	 * @param landmark
	 */
	public final void setLandmark(java.lang.String landmark)
	{
		setLandmark(getContext(), landmark);
	}

	/**
	 * Set value of Landmark
	 * @param context
	 * @param landmark
	 */
	public final void setLandmark(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String landmark)
	{
		getMendixObject().setValue(context, MemberNames.Landmark.toString(), landmark);
	}

	/**
	 * @return value of Zip
	 */
	public final java.lang.String getZip()
	{
		return getZip(getContext());
	}

	/**
	 * @param context
	 * @return value of Zip
	 */
	public final java.lang.String getZip(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Zip.toString());
	}

	/**
	 * Set value of Zip
	 * @param zip
	 */
	public final void setZip(java.lang.String zip)
	{
		setZip(getContext(), zip);
	}

	/**
	 * Set value of Zip
	 * @param context
	 * @param zip
	 */
	public final void setZip(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String zip)
	{
		getMendixObject().setValue(context, MemberNames.Zip.toString(), zip);
	}

	/**
	 * Set value of RegistrationStatus
	 * @param registrationstatus
	 */
	public final userregistration.proxies.RegistrationStatus getRegistrationStatus()
	{
		return getRegistrationStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of RegistrationStatus
	 */
	public final userregistration.proxies.RegistrationStatus getRegistrationStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.RegistrationStatus.toString());
		if (obj == null) {
			return null;
		}
		return userregistration.proxies.RegistrationStatus.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of RegistrationStatus
	 * @param registrationstatus
	 */
	public final void setRegistrationStatus(userregistration.proxies.RegistrationStatus registrationstatus)
	{
		setRegistrationStatus(getContext(), registrationstatus);
	}

	/**
	 * Set value of RegistrationStatus
	 * @param context
	 * @param registrationstatus
	 */
	public final void setRegistrationStatus(com.mendix.systemwideinterfaces.core.IContext context, userregistration.proxies.RegistrationStatus registrationstatus)
	{
		if (registrationstatus != null) {
			getMendixObject().setValue(context, MemberNames.RegistrationStatus.toString(), registrationstatus.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.RegistrationStatus.toString(), null);
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final customer.proxies.Customer that = (customer.proxies.Customer) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
