// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package customer.proxies;

public class Equipment
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject equipmentMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Customer.Equipment";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		SerialNo("SerialNo"),
		AssetTag("AssetTag"),
		ModelNo("ModelNo"),
		EquipmentType("EquipmentType"),
		MfgDate("MfgDate"),
		PurchaseDate("PurchaseDate"),
		WarrantPeriod("WarrantPeriod"),
		Equipment_ServiceRequest("Customer.Equipment_ServiceRequest");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Equipment(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Equipment(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject equipmentMendixObject)
	{
		if (equipmentMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, equipmentMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.equipmentMendixObject = equipmentMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Equipment.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static customer.proxies.Equipment initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return customer.proxies.Equipment.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static customer.proxies.Equipment initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new customer.proxies.Equipment(context, mendixObject);
	}

	public static customer.proxies.Equipment load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return customer.proxies.Equipment.initialize(context, mendixObject);
	}

	public static java.util.List<customer.proxies.Equipment> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> customer.proxies.Equipment.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of SerialNo
	 */
	public final java.lang.String getSerialNo()
	{
		return getSerialNo(getContext());
	}

	/**
	 * @param context
	 * @return value of SerialNo
	 */
	public final java.lang.String getSerialNo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SerialNo.toString());
	}

	/**
	 * Set value of SerialNo
	 * @param serialno
	 */
	public final void setSerialNo(java.lang.String serialno)
	{
		setSerialNo(getContext(), serialno);
	}

	/**
	 * Set value of SerialNo
	 * @param context
	 * @param serialno
	 */
	public final void setSerialNo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String serialno)
	{
		getMendixObject().setValue(context, MemberNames.SerialNo.toString(), serialno);
	}

	/**
	 * @return value of AssetTag
	 */
	public final java.lang.String getAssetTag()
	{
		return getAssetTag(getContext());
	}

	/**
	 * @param context
	 * @return value of AssetTag
	 */
	public final java.lang.String getAssetTag(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AssetTag.toString());
	}

	/**
	 * Set value of AssetTag
	 * @param assettag
	 */
	public final void setAssetTag(java.lang.String assettag)
	{
		setAssetTag(getContext(), assettag);
	}

	/**
	 * Set value of AssetTag
	 * @param context
	 * @param assettag
	 */
	public final void setAssetTag(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String assettag)
	{
		getMendixObject().setValue(context, MemberNames.AssetTag.toString(), assettag);
	}

	/**
	 * @return value of ModelNo
	 */
	public final java.lang.String getModelNo()
	{
		return getModelNo(getContext());
	}

	/**
	 * @param context
	 * @return value of ModelNo
	 */
	public final java.lang.String getModelNo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ModelNo.toString());
	}

	/**
	 * Set value of ModelNo
	 * @param modelno
	 */
	public final void setModelNo(java.lang.String modelno)
	{
		setModelNo(getContext(), modelno);
	}

	/**
	 * Set value of ModelNo
	 * @param context
	 * @param modelno
	 */
	public final void setModelNo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String modelno)
	{
		getMendixObject().setValue(context, MemberNames.ModelNo.toString(), modelno);
	}

	/**
	 * @return value of EquipmentType
	 */
	public final java.lang.String getEquipmentType()
	{
		return getEquipmentType(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentType
	 */
	public final java.lang.String getEquipmentType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EquipmentType.toString());
	}

	/**
	 * Set value of EquipmentType
	 * @param equipmenttype
	 */
	public final void setEquipmentType(java.lang.String equipmenttype)
	{
		setEquipmentType(getContext(), equipmenttype);
	}

	/**
	 * Set value of EquipmentType
	 * @param context
	 * @param equipmenttype
	 */
	public final void setEquipmentType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String equipmenttype)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentType.toString(), equipmenttype);
	}

	/**
	 * @return value of MfgDate
	 */
	public final java.util.Date getMfgDate()
	{
		return getMfgDate(getContext());
	}

	/**
	 * @param context
	 * @return value of MfgDate
	 */
	public final java.util.Date getMfgDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.MfgDate.toString());
	}

	/**
	 * Set value of MfgDate
	 * @param mfgdate
	 */
	public final void setMfgDate(java.util.Date mfgdate)
	{
		setMfgDate(getContext(), mfgdate);
	}

	/**
	 * Set value of MfgDate
	 * @param context
	 * @param mfgdate
	 */
	public final void setMfgDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date mfgdate)
	{
		getMendixObject().setValue(context, MemberNames.MfgDate.toString(), mfgdate);
	}

	/**
	 * @return value of PurchaseDate
	 */
	public final java.util.Date getPurchaseDate()
	{
		return getPurchaseDate(getContext());
	}

	/**
	 * @param context
	 * @return value of PurchaseDate
	 */
	public final java.util.Date getPurchaseDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.PurchaseDate.toString());
	}

	/**
	 * Set value of PurchaseDate
	 * @param purchasedate
	 */
	public final void setPurchaseDate(java.util.Date purchasedate)
	{
		setPurchaseDate(getContext(), purchasedate);
	}

	/**
	 * Set value of PurchaseDate
	 * @param context
	 * @param purchasedate
	 */
	public final void setPurchaseDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date purchasedate)
	{
		getMendixObject().setValue(context, MemberNames.PurchaseDate.toString(), purchasedate);
	}

	/**
	 * Set value of WarrantPeriod
	 * @param warrantperiod
	 */
	public final customer.proxies.Enum_WarrantPeriod getWarrantPeriod()
	{
		return getWarrantPeriod(getContext());
	}

	/**
	 * @param context
	 * @return value of WarrantPeriod
	 */
	public final customer.proxies.Enum_WarrantPeriod getWarrantPeriod(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.WarrantPeriod.toString());
		if (obj == null) {
			return null;
		}
		return customer.proxies.Enum_WarrantPeriod.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of WarrantPeriod
	 * @param warrantperiod
	 */
	public final void setWarrantPeriod(customer.proxies.Enum_WarrantPeriod warrantperiod)
	{
		setWarrantPeriod(getContext(), warrantperiod);
	}

	/**
	 * Set value of WarrantPeriod
	 * @param context
	 * @param warrantperiod
	 */
	public final void setWarrantPeriod(com.mendix.systemwideinterfaces.core.IContext context, customer.proxies.Enum_WarrantPeriod warrantperiod)
	{
		if (warrantperiod != null) {
			getMendixObject().setValue(context, MemberNames.WarrantPeriod.toString(), warrantperiod.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.WarrantPeriod.toString(), null);
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Equipment_ServiceRequest
	 */
	public final customer.proxies.ServiceRequest getEquipment_ServiceRequest() throws com.mendix.core.CoreException
	{
		return getEquipment_ServiceRequest(getContext());
	}

	/**
	 * @param context
	 * @return value of Equipment_ServiceRequest
	 * @throws com.mendix.core.CoreException
	 */
	public final customer.proxies.ServiceRequest getEquipment_ServiceRequest(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		customer.proxies.ServiceRequest result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Equipment_ServiceRequest.toString());
		if (identifier != null) {
			result = customer.proxies.ServiceRequest.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Equipment_ServiceRequest
	 * @param equipment_servicerequest
	 */
	public final void setEquipment_ServiceRequest(customer.proxies.ServiceRequest equipment_servicerequest)
	{
		setEquipment_ServiceRequest(getContext(), equipment_servicerequest);
	}

	/**
	 * Set value of Equipment_ServiceRequest
	 * @param context
	 * @param equipment_servicerequest
	 */
	public final void setEquipment_ServiceRequest(com.mendix.systemwideinterfaces.core.IContext context, customer.proxies.ServiceRequest equipment_servicerequest)
	{
		if (equipment_servicerequest == null) {
			getMendixObject().setValue(context, MemberNames.Equipment_ServiceRequest.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Equipment_ServiceRequest.toString(), equipment_servicerequest.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return equipmentMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final customer.proxies.Equipment that = (customer.proxies.Equipment) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
