// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package customer.proxies;

public class ServiceRequest
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject serviceRequestMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Customer.ServiceRequest";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		SRNo("SRNo"),
		Sequence("Sequence"),
		_Type("_Type"),
		Email("Email"),
		PhoneNumber("PhoneNumber"),
		Address1("Address1"),
		Address2("Address2"),
		City("City"),
		State("State"),
		Landmark("Landmark"),
		Zip("Zip"),
		RequestStatus("RequestStatus"),
		TotalCost("TotalCost"),
		ServiceRequest_Customer("Customer.ServiceRequest_Customer"),
		Equipment_ServiceRequest("Customer.Equipment_ServiceRequest"),
		ServiceRequest_AssignToTechnician("Customer.ServiceRequest_AssignToTechnician");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ServiceRequest(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ServiceRequest(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject serviceRequestMendixObject)
	{
		if (serviceRequestMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, serviceRequestMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.serviceRequestMendixObject = serviceRequestMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ServiceRequest.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static customer.proxies.ServiceRequest initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return customer.proxies.ServiceRequest.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static customer.proxies.ServiceRequest initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new customer.proxies.ServiceRequest(context, mendixObject);
	}

	public static customer.proxies.ServiceRequest load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return customer.proxies.ServiceRequest.initialize(context, mendixObject);
	}

	public static java.util.List<customer.proxies.ServiceRequest> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> customer.proxies.ServiceRequest.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of SRNo
	 */
	public final java.lang.String getSRNo()
	{
		return getSRNo(getContext());
	}

	/**
	 * @param context
	 * @return value of SRNo
	 */
	public final java.lang.String getSRNo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SRNo.toString());
	}

	/**
	 * Set value of SRNo
	 * @param srno
	 */
	public final void setSRNo(java.lang.String srno)
	{
		setSRNo(getContext(), srno);
	}

	/**
	 * Set value of SRNo
	 * @param context
	 * @param srno
	 */
	public final void setSRNo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String srno)
	{
		getMendixObject().setValue(context, MemberNames.SRNo.toString(), srno);
	}

	/**
	 * @return value of Sequence
	 */
	public final java.lang.Long getSequence()
	{
		return getSequence(getContext());
	}

	/**
	 * @param context
	 * @return value of Sequence
	 */
	public final java.lang.Long getSequence(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.Sequence.toString());
	}

	/**
	 * Set value of Sequence
	 * @param sequence
	 */
	public final void setSequence(java.lang.Long sequence)
	{
		setSequence(getContext(), sequence);
	}

	/**
	 * Set value of Sequence
	 * @param context
	 * @param sequence
	 */
	public final void setSequence(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long sequence)
	{
		getMendixObject().setValue(context, MemberNames.Sequence.toString(), sequence);
	}

	/**
	 * Set value of _Type
	 * @param _type
	 */
	public final customer.proxies.Enum_ServiceType get_Type()
	{
		return get_Type(getContext());
	}

	/**
	 * @param context
	 * @return value of _Type
	 */
	public final customer.proxies.Enum_ServiceType get_Type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames._Type.toString());
		if (obj == null) {
			return null;
		}
		return customer.proxies.Enum_ServiceType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of _Type
	 * @param _type
	 */
	public final void set_Type(customer.proxies.Enum_ServiceType _type)
	{
		set_Type(getContext(), _type);
	}

	/**
	 * Set value of _Type
	 * @param context
	 * @param _type
	 */
	public final void set_Type(com.mendix.systemwideinterfaces.core.IContext context, customer.proxies.Enum_ServiceType _type)
	{
		if (_type != null) {
			getMendixObject().setValue(context, MemberNames._Type.toString(), _type.toString());
		} else {
			getMendixObject().setValue(context, MemberNames._Type.toString(), null);
		}
	}

	/**
	 * @return value of Email
	 */
	public final java.lang.String getEmail()
	{
		return getEmail(getContext());
	}

	/**
	 * @param context
	 * @return value of Email
	 */
	public final java.lang.String getEmail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Email.toString());
	}

	/**
	 * Set value of Email
	 * @param email
	 */
	public final void setEmail(java.lang.String email)
	{
		setEmail(getContext(), email);
	}

	/**
	 * Set value of Email
	 * @param context
	 * @param email
	 */
	public final void setEmail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String email)
	{
		getMendixObject().setValue(context, MemberNames.Email.toString(), email);
	}

	/**
	 * @return value of PhoneNumber
	 */
	public final java.lang.String getPhoneNumber()
	{
		return getPhoneNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of PhoneNumber
	 */
	public final java.lang.String getPhoneNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PhoneNumber.toString());
	}

	/**
	 * Set value of PhoneNumber
	 * @param phonenumber
	 */
	public final void setPhoneNumber(java.lang.String phonenumber)
	{
		setPhoneNumber(getContext(), phonenumber);
	}

	/**
	 * Set value of PhoneNumber
	 * @param context
	 * @param phonenumber
	 */
	public final void setPhoneNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String phonenumber)
	{
		getMendixObject().setValue(context, MemberNames.PhoneNumber.toString(), phonenumber);
	}

	/**
	 * @return value of Address1
	 */
	public final java.lang.String getAddress1()
	{
		return getAddress1(getContext());
	}

	/**
	 * @param context
	 * @return value of Address1
	 */
	public final java.lang.String getAddress1(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Address1.toString());
	}

	/**
	 * Set value of Address1
	 * @param address1
	 */
	public final void setAddress1(java.lang.String address1)
	{
		setAddress1(getContext(), address1);
	}

	/**
	 * Set value of Address1
	 * @param context
	 * @param address1
	 */
	public final void setAddress1(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String address1)
	{
		getMendixObject().setValue(context, MemberNames.Address1.toString(), address1);
	}

	/**
	 * @return value of Address2
	 */
	public final java.lang.String getAddress2()
	{
		return getAddress2(getContext());
	}

	/**
	 * @param context
	 * @return value of Address2
	 */
	public final java.lang.String getAddress2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Address2.toString());
	}

	/**
	 * Set value of Address2
	 * @param address2
	 */
	public final void setAddress2(java.lang.String address2)
	{
		setAddress2(getContext(), address2);
	}

	/**
	 * Set value of Address2
	 * @param context
	 * @param address2
	 */
	public final void setAddress2(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String address2)
	{
		getMendixObject().setValue(context, MemberNames.Address2.toString(), address2);
	}

	/**
	 * @return value of City
	 */
	public final java.lang.String getCity()
	{
		return getCity(getContext());
	}

	/**
	 * @param context
	 * @return value of City
	 */
	public final java.lang.String getCity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.City.toString());
	}

	/**
	 * Set value of City
	 * @param city
	 */
	public final void setCity(java.lang.String city)
	{
		setCity(getContext(), city);
	}

	/**
	 * Set value of City
	 * @param context
	 * @param city
	 */
	public final void setCity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String city)
	{
		getMendixObject().setValue(context, MemberNames.City.toString(), city);
	}

	/**
	 * @return value of State
	 */
	public final java.lang.String getState()
	{
		return getState(getContext());
	}

	/**
	 * @param context
	 * @return value of State
	 */
	public final java.lang.String getState(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.State.toString());
	}

	/**
	 * Set value of State
	 * @param state
	 */
	public final void setState(java.lang.String state)
	{
		setState(getContext(), state);
	}

	/**
	 * Set value of State
	 * @param context
	 * @param state
	 */
	public final void setState(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String state)
	{
		getMendixObject().setValue(context, MemberNames.State.toString(), state);
	}

	/**
	 * @return value of Landmark
	 */
	public final java.lang.String getLandmark()
	{
		return getLandmark(getContext());
	}

	/**
	 * @param context
	 * @return value of Landmark
	 */
	public final java.lang.String getLandmark(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Landmark.toString());
	}

	/**
	 * Set value of Landmark
	 * @param landmark
	 */
	public final void setLandmark(java.lang.String landmark)
	{
		setLandmark(getContext(), landmark);
	}

	/**
	 * Set value of Landmark
	 * @param context
	 * @param landmark
	 */
	public final void setLandmark(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String landmark)
	{
		getMendixObject().setValue(context, MemberNames.Landmark.toString(), landmark);
	}

	/**
	 * @return value of Zip
	 */
	public final java.lang.String getZip()
	{
		return getZip(getContext());
	}

	/**
	 * @param context
	 * @return value of Zip
	 */
	public final java.lang.String getZip(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Zip.toString());
	}

	/**
	 * Set value of Zip
	 * @param zip
	 */
	public final void setZip(java.lang.String zip)
	{
		setZip(getContext(), zip);
	}

	/**
	 * Set value of Zip
	 * @param context
	 * @param zip
	 */
	public final void setZip(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String zip)
	{
		getMendixObject().setValue(context, MemberNames.Zip.toString(), zip);
	}

	/**
	 * Set value of RequestStatus
	 * @param requeststatus
	 */
	public final customer.proxies.Enum_RequestStatus getRequestStatus()
	{
		return getRequestStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestStatus
	 */
	public final customer.proxies.Enum_RequestStatus getRequestStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.RequestStatus.toString());
		if (obj == null) {
			return null;
		}
		return customer.proxies.Enum_RequestStatus.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of RequestStatus
	 * @param requeststatus
	 */
	public final void setRequestStatus(customer.proxies.Enum_RequestStatus requeststatus)
	{
		setRequestStatus(getContext(), requeststatus);
	}

	/**
	 * Set value of RequestStatus
	 * @param context
	 * @param requeststatus
	 */
	public final void setRequestStatus(com.mendix.systemwideinterfaces.core.IContext context, customer.proxies.Enum_RequestStatus requeststatus)
	{
		if (requeststatus != null) {
			getMendixObject().setValue(context, MemberNames.RequestStatus.toString(), requeststatus.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.RequestStatus.toString(), null);
		}
	}

	/**
	 * @return value of TotalCost
	 */
	public final java.math.BigDecimal getTotalCost()
	{
		return getTotalCost(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalCost
	 */
	public final java.math.BigDecimal getTotalCost(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.TotalCost.toString());
	}

	/**
	 * Set value of TotalCost
	 * @param totalcost
	 */
	public final void setTotalCost(java.math.BigDecimal totalcost)
	{
		setTotalCost(getContext(), totalcost);
	}

	/**
	 * Set value of TotalCost
	 * @param context
	 * @param totalcost
	 */
	public final void setTotalCost(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal totalcost)
	{
		getMendixObject().setValue(context, MemberNames.TotalCost.toString(), totalcost);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ServiceRequest_Customer
	 */
	public final customer.proxies.Customer getServiceRequest_Customer() throws com.mendix.core.CoreException
	{
		return getServiceRequest_Customer(getContext());
	}

	/**
	 * @param context
	 * @return value of ServiceRequest_Customer
	 * @throws com.mendix.core.CoreException
	 */
	public final customer.proxies.Customer getServiceRequest_Customer(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		customer.proxies.Customer result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ServiceRequest_Customer.toString());
		if (identifier != null) {
			result = customer.proxies.Customer.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ServiceRequest_Customer
	 * @param servicerequest_customer
	 */
	public final void setServiceRequest_Customer(customer.proxies.Customer servicerequest_customer)
	{
		setServiceRequest_Customer(getContext(), servicerequest_customer);
	}

	/**
	 * Set value of ServiceRequest_Customer
	 * @param context
	 * @param servicerequest_customer
	 */
	public final void setServiceRequest_Customer(com.mendix.systemwideinterfaces.core.IContext context, customer.proxies.Customer servicerequest_customer)
	{
		if (servicerequest_customer == null) {
			getMendixObject().setValue(context, MemberNames.ServiceRequest_Customer.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ServiceRequest_Customer.toString(), servicerequest_customer.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Equipment_ServiceRequest
	 */
	public final customer.proxies.Equipment getEquipment_ServiceRequest() throws com.mendix.core.CoreException
	{
		return getEquipment_ServiceRequest(getContext());
	}

	/**
	 * @param context
	 * @return value of Equipment_ServiceRequest
	 * @throws com.mendix.core.CoreException
	 */
	public final customer.proxies.Equipment getEquipment_ServiceRequest(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		customer.proxies.Equipment result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Equipment_ServiceRequest.toString());
		if (identifier != null) {
			result = customer.proxies.Equipment.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Equipment_ServiceRequest
	 * @param equipment_servicerequest
	 */
	public final void setEquipment_ServiceRequest(customer.proxies.Equipment equipment_servicerequest)
	{
		setEquipment_ServiceRequest(getContext(), equipment_servicerequest);
	}

	/**
	 * Set value of Equipment_ServiceRequest
	 * @param context
	 * @param equipment_servicerequest
	 */
	public final void setEquipment_ServiceRequest(com.mendix.systemwideinterfaces.core.IContext context, customer.proxies.Equipment equipment_servicerequest)
	{
		if (equipment_servicerequest == null) {
			getMendixObject().setValue(context, MemberNames.Equipment_ServiceRequest.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Equipment_ServiceRequest.toString(), equipment_servicerequest.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ServiceRequest_AssignToTechnician
	 */
	public final administration.proxies.Account getServiceRequest_AssignToTechnician() throws com.mendix.core.CoreException
	{
		return getServiceRequest_AssignToTechnician(getContext());
	}

	/**
	 * @param context
	 * @return value of ServiceRequest_AssignToTechnician
	 * @throws com.mendix.core.CoreException
	 */
	public final administration.proxies.Account getServiceRequest_AssignToTechnician(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		administration.proxies.Account result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ServiceRequest_AssignToTechnician.toString());
		if (identifier != null) {
			result = administration.proxies.Account.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ServiceRequest_AssignToTechnician
	 * @param servicerequest_assigntotechnician
	 */
	public final void setServiceRequest_AssignToTechnician(administration.proxies.Account servicerequest_assigntotechnician)
	{
		setServiceRequest_AssignToTechnician(getContext(), servicerequest_assigntotechnician);
	}

	/**
	 * Set value of ServiceRequest_AssignToTechnician
	 * @param context
	 * @param servicerequest_assigntotechnician
	 */
	public final void setServiceRequest_AssignToTechnician(com.mendix.systemwideinterfaces.core.IContext context, administration.proxies.Account servicerequest_assigntotechnician)
	{
		if (servicerequest_assigntotechnician == null) {
			getMendixObject().setValue(context, MemberNames.ServiceRequest_AssignToTechnician.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ServiceRequest_AssignToTechnician.toString(), servicerequest_assigntotechnician.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return serviceRequestMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final customer.proxies.ServiceRequest that = (customer.proxies.ServiceRequest) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
