// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package administrator.proxies;

public class Coord
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject coordMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Administrator.Coord";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Lon("Lon"),
		Lat("Lat"),
		Coord_Root("Administrator.Coord_Root");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Coord(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Coord(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject coordMendixObject)
	{
		if (coordMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, coordMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.coordMendixObject = coordMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Coord.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static administrator.proxies.Coord initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return administrator.proxies.Coord.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static administrator.proxies.Coord initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new administrator.proxies.Coord(context, mendixObject);
	}

	public static administrator.proxies.Coord load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return administrator.proxies.Coord.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Lon
	 */
	public final java.math.BigDecimal getLon()
	{
		return getLon(getContext());
	}

	/**
	 * @param context
	 * @return value of Lon
	 */
	public final java.math.BigDecimal getLon(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Lon.toString());
	}

	/**
	 * Set value of Lon
	 * @param lon
	 */
	public final void setLon(java.math.BigDecimal lon)
	{
		setLon(getContext(), lon);
	}

	/**
	 * Set value of Lon
	 * @param context
	 * @param lon
	 */
	public final void setLon(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal lon)
	{
		getMendixObject().setValue(context, MemberNames.Lon.toString(), lon);
	}

	/**
	 * @return value of Lat
	 */
	public final java.math.BigDecimal getLat()
	{
		return getLat(getContext());
	}

	/**
	 * @param context
	 * @return value of Lat
	 */
	public final java.math.BigDecimal getLat(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Lat.toString());
	}

	/**
	 * Set value of Lat
	 * @param lat
	 */
	public final void setLat(java.math.BigDecimal lat)
	{
		setLat(getContext(), lat);
	}

	/**
	 * Set value of Lat
	 * @param context
	 * @param lat
	 */
	public final void setLat(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal lat)
	{
		getMendixObject().setValue(context, MemberNames.Lat.toString(), lat);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Coord_Root
	 */
	public final administrator.proxies.Root getCoord_Root() throws com.mendix.core.CoreException
	{
		return getCoord_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of Coord_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final administrator.proxies.Root getCoord_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		administrator.proxies.Root result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Coord_Root.toString());
		if (identifier != null) {
			result = administrator.proxies.Root.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Coord_Root
	 * @param coord_root
	 */
	public final void setCoord_Root(administrator.proxies.Root coord_root)
	{
		setCoord_Root(getContext(), coord_root);
	}

	/**
	 * Set value of Coord_Root
	 * @param context
	 * @param coord_root
	 */
	public final void setCoord_Root(com.mendix.systemwideinterfaces.core.IContext context, administrator.proxies.Root coord_root)
	{
		if (coord_root == null) {
			getMendixObject().setValue(context, MemberNames.Coord_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Coord_Root.toString(), coord_root.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return coordMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final administrator.proxies.Coord that = (administrator.proxies.Coord) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
