// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package administrator.proxies;

public class Sys
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject sysMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Administrator.Sys";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Country("Country"),
		Sunrise("Sunrise"),
		Sunset("Sunset"),
		Sys_Root("Administrator.Sys_Root");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Sys(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Sys(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject sysMendixObject)
	{
		if (sysMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, sysMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.sysMendixObject = sysMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Sys.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static administrator.proxies.Sys initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return administrator.proxies.Sys.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static administrator.proxies.Sys initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new administrator.proxies.Sys(context, mendixObject);
	}

	public static administrator.proxies.Sys load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return administrator.proxies.Sys.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Country
	 */
	public final java.lang.String getCountry()
	{
		return getCountry(getContext());
	}

	/**
	 * @param context
	 * @return value of Country
	 */
	public final java.lang.String getCountry(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Country.toString());
	}

	/**
	 * Set value of Country
	 * @param country
	 */
	public final void setCountry(java.lang.String country)
	{
		setCountry(getContext(), country);
	}

	/**
	 * Set value of Country
	 * @param context
	 * @param country
	 */
	public final void setCountry(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String country)
	{
		getMendixObject().setValue(context, MemberNames.Country.toString(), country);
	}

	/**
	 * @return value of Sunrise
	 */
	public final java.lang.Integer getSunrise()
	{
		return getSunrise(getContext());
	}

	/**
	 * @param context
	 * @return value of Sunrise
	 */
	public final java.lang.Integer getSunrise(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Sunrise.toString());
	}

	/**
	 * Set value of Sunrise
	 * @param sunrise
	 */
	public final void setSunrise(java.lang.Integer sunrise)
	{
		setSunrise(getContext(), sunrise);
	}

	/**
	 * Set value of Sunrise
	 * @param context
	 * @param sunrise
	 */
	public final void setSunrise(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer sunrise)
	{
		getMendixObject().setValue(context, MemberNames.Sunrise.toString(), sunrise);
	}

	/**
	 * @return value of Sunset
	 */
	public final java.lang.Integer getSunset()
	{
		return getSunset(getContext());
	}

	/**
	 * @param context
	 * @return value of Sunset
	 */
	public final java.lang.Integer getSunset(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Sunset.toString());
	}

	/**
	 * Set value of Sunset
	 * @param sunset
	 */
	public final void setSunset(java.lang.Integer sunset)
	{
		setSunset(getContext(), sunset);
	}

	/**
	 * Set value of Sunset
	 * @param context
	 * @param sunset
	 */
	public final void setSunset(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer sunset)
	{
		getMendixObject().setValue(context, MemberNames.Sunset.toString(), sunset);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Sys_Root
	 */
	public final administrator.proxies.Root getSys_Root() throws com.mendix.core.CoreException
	{
		return getSys_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of Sys_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final administrator.proxies.Root getSys_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		administrator.proxies.Root result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Sys_Root.toString());
		if (identifier != null) {
			result = administrator.proxies.Root.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Sys_Root
	 * @param sys_root
	 */
	public final void setSys_Root(administrator.proxies.Root sys_root)
	{
		setSys_Root(getContext(), sys_root);
	}

	/**
	 * Set value of Sys_Root
	 * @param context
	 * @param sys_root
	 */
	public final void setSys_Root(com.mendix.systemwideinterfaces.core.IContext context, administrator.proxies.Root sys_root)
	{
		if (sys_root == null) {
			getMendixObject().setValue(context, MemberNames.Sys_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Sys_Root.toString(), sys_root.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return sysMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final administrator.proxies.Sys that = (administrator.proxies.Sys) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
