// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package administrator.proxies;

public class Wind
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject windMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Administrator.Wind";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Speed("Speed"),
		Deg("Deg"),
		Gust("Gust"),
		Wind_Root("Administrator.Wind_Root");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Wind(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Wind(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject windMendixObject)
	{
		if (windMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, windMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.windMendixObject = windMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Wind.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static administrator.proxies.Wind initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return administrator.proxies.Wind.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static administrator.proxies.Wind initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new administrator.proxies.Wind(context, mendixObject);
	}

	public static administrator.proxies.Wind load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return administrator.proxies.Wind.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Speed
	 */
	public final java.math.BigDecimal getSpeed()
	{
		return getSpeed(getContext());
	}

	/**
	 * @param context
	 * @return value of Speed
	 */
	public final java.math.BigDecimal getSpeed(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Speed.toString());
	}

	/**
	 * Set value of Speed
	 * @param speed
	 */
	public final void setSpeed(java.math.BigDecimal speed)
	{
		setSpeed(getContext(), speed);
	}

	/**
	 * Set value of Speed
	 * @param context
	 * @param speed
	 */
	public final void setSpeed(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal speed)
	{
		getMendixObject().setValue(context, MemberNames.Speed.toString(), speed);
	}

	/**
	 * @return value of Deg
	 */
	public final java.lang.Integer getDeg()
	{
		return getDeg(getContext());
	}

	/**
	 * @param context
	 * @return value of Deg
	 */
	public final java.lang.Integer getDeg(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Deg.toString());
	}

	/**
	 * Set value of Deg
	 * @param deg
	 */
	public final void setDeg(java.lang.Integer deg)
	{
		setDeg(getContext(), deg);
	}

	/**
	 * Set value of Deg
	 * @param context
	 * @param deg
	 */
	public final void setDeg(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer deg)
	{
		getMendixObject().setValue(context, MemberNames.Deg.toString(), deg);
	}

	/**
	 * @return value of Gust
	 */
	public final java.math.BigDecimal getGust()
	{
		return getGust(getContext());
	}

	/**
	 * @param context
	 * @return value of Gust
	 */
	public final java.math.BigDecimal getGust(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Gust.toString());
	}

	/**
	 * Set value of Gust
	 * @param gust
	 */
	public final void setGust(java.math.BigDecimal gust)
	{
		setGust(getContext(), gust);
	}

	/**
	 * Set value of Gust
	 * @param context
	 * @param gust
	 */
	public final void setGust(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal gust)
	{
		getMendixObject().setValue(context, MemberNames.Gust.toString(), gust);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Wind_Root
	 */
	public final administrator.proxies.Root getWind_Root() throws com.mendix.core.CoreException
	{
		return getWind_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of Wind_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final administrator.proxies.Root getWind_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		administrator.proxies.Root result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Wind_Root.toString());
		if (identifier != null) {
			result = administrator.proxies.Root.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Wind_Root
	 * @param wind_root
	 */
	public final void setWind_Root(administrator.proxies.Root wind_root)
	{
		setWind_Root(getContext(), wind_root);
	}

	/**
	 * Set value of Wind_Root
	 * @param context
	 * @param wind_root
	 */
	public final void setWind_Root(com.mendix.systemwideinterfaces.core.IContext context, administrator.proxies.Root wind_root)
	{
		if (wind_root == null) {
			getMendixObject().setValue(context, MemberNames.Wind_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Wind_Root.toString(), wind_root.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return windMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final administrator.proxies.Wind that = (administrator.proxies.Wind) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
